audit_header: false
title: "Myrtle Beach's Best Real Estate Training"
description: Blake Sloan, a top Real Estate Agent in Myrtle Beach, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Blake Sloan
  title:
  license_number:
  about_markdown: |
    The Blake Sloan Team is one of the most advanced and highly ranked real estate teams in the world. They were recently ranked by the Wall Street Journal as one of the Top 50 Real Estate Teams In North America, coming in at #37, and #1 in the State Of South Carolina.

    Blake Sloan's unmatched marketing and innovation in the real estate world has landed him national attention with recognition such as "Forbes Magazine Top 30 Under 30", Real Estate Magazine's Top 30 Under 30, and has been featured in both national and local news outlets like NBC, Fox, and others.
  market: Myrtle Beach
  brand: Sloan Realty Group
  brokerage:
  address: 3120 Waccamaw Blvd Suite C<br>Myrtle Beach, SC 29579
  phone: 843-997-0004
  phone_type:
  phone2:
  phone2_type:
  email: blake@srgmail.com
  url: http://www.sloanrealtygroup.net

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/SloanRealty/
  linkedin_url: http://www.linkedin.com/in/jblakesloan
  gplus_url:
  youtube_url: http://www.youtube.com/user/SloanRealtyGroup?feature=watch
  twitter_url: https://twitter.com/SloanRealty
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0054a5'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
